import { ThemeProvider } from '@/components/providers/theme-provider';
import './globals.css';
import type { Metadata } from 'next';
import {
  CalendarIcon,
  ListTodoIcon,
  LucideIcon,
  SearchIcon,
  LucideProps,
} from 'lucide-react';
import { MouseEventHandler } from 'react';
import { cn } from '@/lib/utils';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <html lang="en" suppressHydrationWarning className="h-full">
        <head />
        <body className="flex h-full">
          <nav className="flex flex-col bg-background px-0.5 py-1">
            <NavMenuButton Icon={ListTodoIcon} active />
            <NavMenuButton Icon={CalendarIcon} />
            <NavMenuButton Icon={SearchIcon} />
          </nav>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
        </body>
      </html>
    </>
  );
}

function NavMenuButton({
  Icon,
  active = false,
  onClick,
  ...iconProps
}: LucideProps & {
  Icon: LucideIcon;
  active?: boolean;
  onClick?: MouseEventHandler<HTMLButtonElement>;
}) {
  return (
    <button
      className={cn('p-2 opacity-50 hover:opacity-80', {
        'opacity-100': active,
      })}
      disabled={active}
      onClick={onClick}
    >
      <Icon {...iconProps} strokeWidth={2.5} />
    </button>
  );
}
